"""Add is_admin field to users table

Revision ID: 433e2fd9274d
Revises: 
Create Date: 2025-11-15 12:39:24.189145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433e2fd9274d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")
    
    # Make column not nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
